# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: Native SQL Engine TPC-H Suite

on:
  issue_comment:
    types: [created, edited]

jobs:
  ram-usage-test:
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '@github-actions ram-usage-test') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_URL="${{ github.event.issue.pull_request.url }}"
          PR_NUM=${PR_URL##*/}
          echo "Checking out from PR #$PR_NUM based on URL: $PR_URL"
          hub pr checkout $PR_NUM
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: iterative/setup-cml@v1
        with:
          version: latest
      - run: sudo swapoff -a
      - run: free
      - run: sudo apt-get update
      - run: sudo apt-get install cmake
      - run: sudo apt-get install libboost-all-dev
      - name: Install OAP optimized Arrow
        run: |
          cd /tmp
          git clone https://github.com/oap-project/arrow.git
          cd arrow && git checkout arrow-4.0.0-oap-1.3.1 && cd cpp
          mkdir build && cd build
          cmake .. -DARROW_JNI=ON -DARROW_GANDIVA_JAVA=ON -DARROW_GANDIVA=ON -DARROW_PARQUET=ON -DARROW_ORC=ON -DARROW_CSV=ON -DARROW_HDFS=ON -DARROW_FILESYSTEM=ON -DARROW_WITH_SNAPPY=ON -DARROW_JSON=ON -DARROW_DATASET=ON -DARROW_WITH_LZ4=ON -DARROW_JEMALLOC=OFF && make -j2
          sudo make install
          cd ../../java
          mvn clean install -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -P arrow-jni -am -Darrow.cpp.build.dir=/tmp/arrow/cpp/build/release/ -DskipTests -Dcheckstyle.skip
      - name: Run Maven tests - BHJ
        run: |
          mvn test -B -P full-scala-compiler -Dbuild_arrow=OFF -pl native-sql-engine/core/ -am -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -DmembersOnlySuites=com.intel.oap.tpc.h -DtagsToInclude=com.intel.oap.tags.BroadcastHashJoinMode -DargLine="-Xmx1G -XX:MaxDirectMemorySize=500M -Dio.netty.allocator.numDirectArena=1"
        env:
          MALLOC_ARENA_MAX: "4"
          MAVEN_OPTS: "-Xmx1G"
          COMMENT_TEXT_OUTPUT_PATH: "/tmp/comment_text_1.txt"
          COMMENT_IMAGE_OUTPUT_PATH: "/tmp/comment_image_1.png"
          ENABLE_TPCH_TESTS: "true"
      - name: Run Maven tests - SMJ
        run: |
          mvn test -B -P full-scala-compiler -Dbuild_arrow=OFF -pl native-sql-engine/core/ -am -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -DmembersOnlySuites=com.intel.oap.tpc.h -DtagsToInclude=com.intel.oap.tags.SortMergeJoinMode -DargLine="-Xmx1G -XX:MaxDirectMemorySize=500M -Dio.netty.allocator.numDirectArena=1"
        env:
          MALLOC_ARENA_MAX: "4"
          MAVEN_OPTS: "-Xmx1G"
          COMMENT_TEXT_OUTPUT_PATH: "/tmp/comment_text_2.txt"
          COMMENT_IMAGE_OUTPUT_PATH: "/tmp/comment_image_2.png"
          ENABLE_TPCH_TESTS: "true"
      - run: |
          cml-publish /tmp/comment_image_1.png --md > /tmp/comment.md
          cml-publish /tmp/comment_image_2.png --md >> /tmp/comment.md
      - name: Run Maven tests - Report
        run: |
          mvn test -B -P full-scala-compiler -Dbuild_arrow=OFF -Dbuild_protobuf=OFF -pl native-sql-engine/core/ -am -DmembersOnlySuites=com.intel.oap.tpc.h -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -DtagsToInclude=com.intel.oap.tags.CommentOnContextPR -Dexec.skip=true
        env:
          PR_URL: ${{ github.event.issue.pull_request.url }}
          MAVEN_OPTS: "-Xmx1G"
          COMMENT_CONTENT_PATH: "/tmp/comment.md"
          GITHUB_TOKEN: ${{ github.token }}
          ENABLE_TPCH_TESTS: "true"
